import type { NextPage } from "next"
import Head from "next/head"
import { QRCodeSVG } from 'qrcode.react'
import { useState } from 'react'
import Modal from 'react-modal'


Modal.setAppElement('#__next')

const Home: NextPage = () => {

  const [modalIsOpen, setModalIsOpen] = useState(false)

  function openModal() {
    setModalIsOpen(true)
  }

  function closeModal() {
    setModalIsOpen(false)
  }

  return (
    <>
      <Head>
        <title>QR Code Playground</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>

        <button onClick={openModal}>Open Modal</button>

        <Modal
          isOpen={modalIsOpen}
          onRequestClose={closeModal} // clicking on overlay or pressing ESC

          /** default styles (more or less) translated to tailwind */
          // overlayClassName='fixed top-0 left-0 right-0 bottom-0 bg-white/[.75]'
          // className='absolute top-10 left-10 right-10 bottom-10 border border-gray-600 rounded bg-gray-100 overflow-auto outline-none p-5'

          /** custom styles: the overlay has Modal as its only child, so it can be easily centered with flex */
          overlayClassName='fixed top-0 left-0 right-0 bottom-0 bg-white/[.75] flex justify-center items-center'
          className='border border-gray-600 rounded bg-gray-100 overflow-auto outline-none p-5'

        >
          <div className='flex justify-end items-center'>
            <button onClick={closeModal}>X</button>
          </div>

          <div className='flex flex-col justify-center items-center border border-gray-600 rounded bg-white p-2'>
            <h2 className='text-green-500 text-lg font-bold mb-1'>Lost and Found</h2>
            <div>100% anonymous</div>
            <div>Scan to send a message to the owner.</div>
            <QRCodeSVG className='m-3' value="https://reactjs.org/" />
          </div>

          <div>
            <button>Download as PNG</button>
            <button>Download as PDF</button>
            <button>Copy to clipboard</button>
          </div>

        </Modal>

      </div>
    </>
  )
}

export default Home
